name: test
on: repository_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: git clone https://github.com/gatomek/flashcards-data.git
      - run: npm install
      - run: node app/drop_entries
      - run: node app/upload_entries