name: test
on:
   repository_dispatch:
   workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - run: pwd
      - run: ls -l
      - run: ls -l ..
      - run: node app/drop_entries
      - run: node app/upload_entries
