name: test

on:
   push:
   repository_dispatch:
   workflow_dispatch:
  
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: uploader

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/checkout@main
        with:
          repository: gatomek/flashcards-data
          path: data

      - run: npm install
        working-directory: ./uploader

      - run: node uploader/app/drop_entries
        env:
           MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}

      - run: node uploader/app/upload_entries
        env: 
           MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
           FOLDER: data/data
