name: test
on:
   repository_dispatch:
   workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - run: mkdir data
      - run: mkdir uploader
      - run: git clone https://github.com/gatomek/flashcards-data.git
        working-directory: data
      - run: git clone https://github.com/gatomek/flashcards-mongodb-data-uploader.git
        working-directory: uploader
      - run: npm install
        working-directory: uploader
      - run: pwd
      - run: ls -l
      - run: ls -l ..
      - run: ls -l ../..


