name: test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: pwd
      - run: git clone https://github.com/gatomek/flashcards-data.git
      - run: git clone https://github.com/gatomek/flashcards-mongodb-data-uploader.git
      - run: ls -l
      - run: cd flashcards-mongodb-data-uploader
      - run: npm install
      - run: node app/drop_entries
      - run: node app/upload_entries