name: test
on:
   repository_dispatch:
   workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/checkout@main
        with:
          name: gatomek/flashcards-data
      - run: npm install
      - run: pwd
      - run: ls -l
      - run: ls -l ..
      - run: node app/drop_entries
      - run: node app/upload_entries